version: "{build}"

image: Visual Studio 2019

environment:
  QT5_ROOT_DIRECTORY: C:\Qt\5.13.2
  PYTHON_HOME: C:\Python38

install:
  # Initialize thirdparty dependencies (remove with Conan integration)
  - git submodule update --init --recursive

  # Install build requirements
  - choco install doxygen.install
  - choco install wixtoolset
  - refreshenv

build_script:
  - mkdir _build
  - cd _build
  - cmake .. -G "Visual Studio 16 2019" -A x64 -DBUILD_TESTS=ON -DBUILD_CSHARP_BINDING=ON -DECAL_THIRDPARTY_BUILD_GTEST=ON -DBUILD_PY_BINDING=ON -DBUILD_DOCS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=_install
  - cmake --build . --parallel --config Release
  - cmake --build . --target documentation_c
  - cmake --build . --target documentation_cpp
  - cpack -C Release
  - cmake --build . --target create_python_egg --config Release
